trigger: none

variables:
  PythonVersion: 'pypy3.7'
  

jobs:
  - job: 'win2019tool'
    displayName: 'Windows Tool Run'
    pool:
      name: azsdk-pool-mms-win-2019-general
      vmImage: MMS2019
    steps:
      - task: UsePythonVersion@0
        displayName: 'Use Python 3.9'
        inputs:
          versionSpec: '3.9'
      - template: /eng/common/testproxy/test-proxy-tool.yml
        parameters:
          runProxy: false
      - pwsh: |
          cat $(Build.SourcesDirectory)/test-proxy.log
        displayName: dump output file

  - job: 'linux2020tool'
    displayName: 'Linux Tool Run'
    pool:
      name: azsdk-pool-mms-ubuntu-2004-general
      vmImage: MMSUbuntu20.04
    steps:
      - task: UsePythonVersion@0
        displayName: 'Use Python pypy3'
        inputs:
          versionSpec: 'pypy3'
      - template: /eng/common/testproxy/test-proxy-tool.yml
        parameters:
          runProxy: false
      - pwsh: |
          cat $(Build.SourcesDirectory)/test-proxy.log
        displayName: dump output file

  - job: 'macos'
    displayName: 'Mac Tool Run'
    pool:
      vmImage: 'macOS-10.15'
    steps:
      - task: UsePythonVersion@0
        displayName: 'Use Python python 3.10'
        inputs:
          versionSpec: '3.10'
      - template: /eng/common/testproxy/test-proxy-tool.yml
        parameters:
          runProxy: false
      - pwsh: |
          cat $(Build.SourcesDirectory)/test-proxy.log
        displayName: dump output file